# Clean and don't fail
install:
  - rm -rf docs || exit 0

# Build the website
script:
  - cd hugo
  - ../binaries/hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $github_token
  on:
    branch: master