baseURL = "https://cafecode.bigelow.org/"
disqusShortname = "kevinguay"
googleAnalytics = "UA-109988049-1"
languageCode = "en-us"
theme = "minimal"
title = "Cafe Code"
[[menu.main]]
name = "blog"
url = "/posts/"
weight = 3
[[menu.main]]
name = "menu"
url = "/menu/"
weight = 2
[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 1
[params]
author = "Bigelow Laboratory"
subtitle = "Cafe Code"
