baseURL = "https://zoom.bigelow.org"
languageCode = "en-us"
title = "Zoom Connect"
theme = "blue"
disqusShortname = "kevinguay"
googleAnalytics = "UA-109988049-1"

[params]
  subtitle = "Bigelow Zoom Connect"
  author = "Kevin Guay"